export const tourData = [
    {
        id: 1,
        city: "Avinyonet del Penedès",
        img: "./img/avinyonet.jpg",
        name: "Ajuntament d'Avinyonet",
        info: "Avinyonet del Penedès és un municipi de la comarca de l'Alt Penedès, amb capital a Avinyó Nou.",
    },
    {
        id: 2,
        city: "Les Cabanyes",
        img: "./img/cabanyes.jpg",
        name: "Esglesia de Sant Valentí",
        info: "Les Cabanyes és un municipi de la comarca de l'Alt Penedès. Està situat al nord-oest de Vilafranca del Penedès.",
    },
    {
        id: 3,
        city: "Castellet i La Gornal",
        img: "./img/castellet.jpg",
        name: "Castell i ermita de Sant Pere",
        info: "Castellet i la Gornal és un municipi de la comarca de l'Alt Penedès",
    },
    {
        id: 4,
        city: "Castellví de la Marca",
        img: "./img/castellvi.jpg",
        name: "Esglesia Parroquial de Sant Sadurní",
        info: "Castellví de la Marca és un terme municipal de la comarca de l'Alt Penedès",
    },
    {
        id: 5,
        city: "Font-rubí",
        img: "./img/fontrubi.jpg",
        name: "Ermita de Santa Maria",
        info: "Font-rubí és un terme municipal de la comarca de l'Alt Penedès, amb capital a Guardiola de Font-rubí.",
    },
    {
        id: 6,
        city: "Gelida",
        img: "./img/gelida.jpg",
        name: "Panoràmica del municipi",
        info: "Gelida és un municipi de la comarca de l'Alt Penedès.",
    },
    {
        id: 7,
        city: "La Granada",
        img: "./img/granada.jpg",
        name: "Esglesia de la Granada",
        info: "La Granada és un municipi de la comarca de l'Alt Penedès. A part del nucli principal de població, el municipi de la Granada també inclou les barriades del Carrer Nou i el Cortei",
    },
    {
        id: 8,
        city: "Mediona",
        img: "./img/mediona.jpg",
        name: "Esglesia castell de Mediona",
        info: "Mediona és un terme municipal de la comarca de l'Alt Penedès. Amb una extensió de 47,6 km² és el segon terme més gran de la comarca",
    },
    {
        id: 9,
        city: "Olesa de Bonesvalls",
        img: "./img/olesa.jpg",
        name: "Panoràmica del municipi",
        info: "Olesa de Bonesvalls és un municipi de la comarca de l'Alt Penedès. Limita amb les comarques del Garraf i amb el Baix Llobregat.",
    },
    {
        id: 10,
        city: "Olèrdola",
        img: "./img/olerdola.jpg",
        name: "Muralla romana d'Olèrdola",
        info: "Olèrdola és un terme municipal de la comarca de l'Alt Penedès, amb capital a Sant Miquel d'Olèrdola. El nom del municipi prové de l'antiga ciutat d'Olèrdola, capital històrica del Penedès que hi havia al turó de Sant Miquel",
    },
    {
        id: 11,
        city: "Pacs del Penedès",
        img: "./img/pacs.jpg",
        name: "Casa de la Vila",
        info: "Pacs del Penedès és un municipi de la comarca de l'Alt Penedès. S'estén a l'esquerra del riu Foix, que en forma el límit occidental. Drena el terme també la riera de Llitrà" ,
    },
    {
        id: 12,
        city: "El Pla del Penedès",
        img: "./img/pla.jpg",
        name: "Plaça de la Vila",
        info: "El Pla del Penedès és un municipi de la comarca de l'Alt Penedès. Està situat a la plana del Penedès, al nord de Vilafranca del Penedès. ",
    },
    {
        id: 13,
        city: "Pontons",
        img: "./img/pontons.jpg",
        name: "Panoràmica de la Vila",
        info: "Pontons és un municipi situat a la part nord-occidental de la comarca de l'Alt Penedès, a la província de Barcelona",
    },
    {
        id: 14,
        city: "Puigdàlber",
        img: "./img/puigdalber.jpg",
        name: "Plaça de l'església de Puigdàlber",
        info: "Escrit amb grafia fonètica Puigdalba, que va ser oficial, està documentat al segle xiv com Puig Alber. El topònim és una contracció de «puig de l'àlber»" 
    },
    {
        id: 15,
        city: "Sant Cugat Sesgarrigues",
        img: "./img/santcugat.jpg",
        name: "Església de Sant Cugat de Sesgarrigues",
        info: "Sant Cugat Sesgarrigues és un municipi de la comarca de l'Alt Penedès. El poble de Sant Cugat Sesgarrigues (266 m, d'altitud) és a la part septentrional del terme",
    },
    {
        id: 16,
        city: "Sant Llorenç d'Hortons",
        img: "./img/santllorens.jpg",
        name: "Panoràmica terme municipal",
        info: "Sant Llorenç d'Hortons és un municipi de la comarca de l'Alt Penedès, de 2.419 habitants. És a l'extrem NE de la comarca, al límit amb l'Anoia i el Baix Llobregat.",
    },
    {
        id: 17,
        city: "Sant Martí Sarroca",
        img: "./img/santmarti.jpg",
        name: "Església de Santa Maria",
        info: "Sant Martí Sarroca és una població i un municipi de la comarca de l'Alt Penedès, situat a la vall del riu de Foix al nord-oest de la capital comarcal.",
    },
    {
        id: 18,
        city: "Sant Pere de Riudebitlles",
        img: "./img/santpere.jpg",
        name: "Panoràmica del poble",
        info: "Sant Pere de Riudebitlles és una vila i municipi de la comarca de l'Alt Penedès.",
    },
    {
        id: 19,
        city: "Sant Quintí de Mediona",
        img: "./img/santquinti.jpg",
        name: "Plaça de l'Esglesia",
        info: "Sant Quintí de Mediona és un poble i municipi de la comarca de l'Alt Penedès. Està situat al nord de la comarca, a la vall mitjana de la riera de Mediona.",
    },
    {
        id: 20,
        city: "Sant Sadurní d'Anoia",
        img: "./img/santsadurni.jpg",
        name: "Plaça de l'Esglesia",
        info: " El terme Sadurní procedeix de l'antropònim llatí Saturninus, diminutiu de 'Saturnus', 'Saturn'. El predicat al riu Anoia, del llatí amnucula, 'rierol'.",
    },
    {
        id: 21,
        city: "Santa Fe del Penedès",
        img: "./img/santafe.jpg",
        name: "Església Parroquial de Santa fe del Penedès",
        info: "Santa Fe és un terme més aviat pla, suaument ondulat, situat en un petit tossal a 240 metres d'altitud.",
    },
    {
        id: 22,
        city: "Santa Margarida i els Monjos",
        img: "./img/monjos.jpg",
        name: "Castell-Convent de Penyafort",
        info: "Santa Margarida i els Monjos és un municipi es troba el sud-oest de la comarca de l'Alt Penedès, al límit amb la del Garraf.",
    },
    {
        id: 23,
        city: "Subirats",
        img: "./img/subirats.jpg",
        name: "Capella de Sant Sebastià",
        info: "Subirats és un municipi de la comarca de l'Alt Penedès limítrof amb les comarques del Baix Llobregat i el Garraf",
    },
    {
        id: 24,
        city: "Terrassola i Lavit",
        img: "./img/torrelavit.jpg",
        name: "Finca Segura Viudas",
        info: "Terrassola i Lavit, oficialment Torrelavit, és un municipi de la comarca de l'Alt Penedès.",
    },
    {
        id: 25,
        city: "Torrelles de Foix",
        img: "./img/torrelles.jpg",
        name: "Cases del nucli urbà",
        info: "És un poble envoltat sobretot per l'entorn natural, a l'oest hi trobem la riera de Pontons, afluent del riu Foix que passa per la localitat. També hi trobem Les Dous, unes fonts amb 35 dolls envoltats per dues grans cascades",
    },
    {
        id: 26,
        city: "Vilafranca del Penedès",
        img: "./img/vilafranca.jpg",
        name: "Monument als Castellers",
        info: "Vilafranca del Penedès és una vila de la vegueria del Penedès, capital de la comarca de l'Alt Penedès.",
    },
    {
        id: 27,
        city: "Vilobí del Penedès",
        img: "./img/vilobi.jpg",
        name: "Pèlags de Vilobí",
        info: "Es troba al sector septentrional de la plana, al nord-oest del terme de Vilafranca, accidentat pels contraforts meridionals de les serres de Font-rubí i de Mediona",
    }
]